"""add end_date filed in tenant

Revision ID: a95a7d3d463a
Revises: 95efd239c43d
Create Date: 2025-11-21 08:35:39.817056+00:00

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a95a7d3d463a'
down_revision: Union[str, None] = '95efd239c43d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'end_date')
    # ### end Alembic commands ###
