"""add chat and chat message tabel

Revision ID: 2bd6521a427d
Revises: a95a7d3d463a
Create Date: 2025-11-24 05:41:54.951990+00:00

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bd6521a427d'
down_revision: Union[str, None] = 'a95a7d3d463a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('dataset_storage_path', sa.String(length=1024), nullable=True))
    op.add_column('tenants', sa.Column('dataset_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'dataset_metadata')
    op.drop_column('tenants', 'dataset_storage_path')
    # ### end Alembic commands ###
